### ISSUE TITLE
Start button doesn't dissapear after clicking

### ISSUE THREAD

**Issue by frisadl** [2022-4J-group-O/Main#8]
I did put the "jump d07" at the end and it works but i don't know how it works.

**Comment by Esu0** [comment]
Kwai

**Comment by Esu0** [comment]
kwsk

**Comment by Esu0** [comment]
このブランチPrologueの関数たちを継承してないんだが

**Comment by Esu0** [comment]
`pop_call()` 関数を使えば直りそう
今日直しておく
